### ISSUE TITLE
Update to node 4.0

### ISSUE THREAD

**Issue by emersion** [nathanjohnson320/node_arm#10]
Just tried the pre-build binary from http://nodejs.org, works fine. Could be cool to have it as a deb package.

**Comment by nathanjohnson320** [comment]
It's on my list of things to do this weekend :+1:

**Comment by oenning** [comment]
Thumbs up. Looking forward to use it.

**Comment by emersion** [comment]
The pre-built binary does not work on the Pi (`node --version` works, but not `node something.js`: segmentation fault). I've just begun to compile it, I'll upload it if it succeeds, so you won't have to re-compile it. ;-)

**Comment by emersion** [comment]
After a loooong compilation, here is the result: http://fs.emersion.fr/public/node/

**Comment by nathanjohnson320** [comment]
When I run node I get 
```
node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by node)
node: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.16' not found (required by node)
```

Just need to upgrade my c libs

**Comment by nathanjohnson320** [comment]
Ok everything looks good here. Thanks for compiling definitely saved me some time!
