### ISSUE TITLE
latest version doesn't work

### ISSUE THREAD

**Issue by Homoran** [nathanjohnson320/node_arm#11]
Yesterday I tried your node-arm, and it worked fine.
today I get this:
<code>root@cubox-i:~# wget http://node-arm.herokuapp.com/node_latest_armhf.deb
--2015-09-13 12:15:33--  http://node-arm.herokuapp.com/node_latest_armhf.deb
Resolving node-arm.herokuapp.com (node-arm.herokuapp.com)... 23.21.201.133
Connecting to node-arm.herokuapp.com (node-arm.herokuapp.com)|23.21.201.133|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5465884 (5.2M) [application/x-debian-package]
Saving to: `node_latest_armhf.deb'

100%[==================================================================================================>] 5,465,884    584K/s   in 9.1s

2015-09-13 12:15:42 (586 KB/s) - `node_latest_armhf.deb' saved [5465884/5465884]

root@cubox-i:~# dpkg -i node_latest_armhf.deb
Selecting previously unselected package node.
(Reading database ... 44095 files and directories currently installed.)
Unpacking node (from node_latest_armhf.deb) ...
Setting up node (4.0.0-1) ...
Processing triggers for man-db ...
root@cubox-i:~# node -v
node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by node)
node: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.16' not found (required by node)</code>

Working on a Cubox i4 with armbian from igor pecovnik

**Comment by nathanjohnson320** [comment]
The newest versions of node only work with gcc version 4.8 or higher so you have to upgrade to Jessie. I put that in the docs on the site 

NOTE: You will have to upgrade to jessie version of debian in order to run latest node!
Replace all instances of "wheezy" in /etc/apt/sources.list
sudo apt-get update
sudo apt-get dist-upgrade
