### ISSUE TITLE
Previous version links broken

### ISSUE THREAD

**Issue by joraff** [nathanjohnson320/node_arm#12]
Specifically, `http://node-arm.herokuapp.com/node_0.12.6_armhf.deb` link is a 404. Will you be able to host these, and for how long? `4.0.0` does not work on 14.04 LTS, for those of us on ubuntu.

**Comment by nathanjohnson320** [comment]
I didn't add this in the documentation but the archived version of node is available at http://node-arm.herokuapp.com/node_archive_armhf.deb

**Comment by joraff** [comment]
I see that, but it's ambiguous as to what version that is. Current - 1?

**Comment by nathanjohnson320** [comment]
0.12.6, you can always grab the file straight from gihub if you need to. They're all in here:
https://github.com/nathanjohnson320/node_arm/tree/master/routes/files

**Comment by joraff** [comment]
> https://github.com/nathanjohnson320/node_arm/tree/master/routes/files

^^ Perfect!
