### ISSUE TITLE
Why is Jessie needed for Node.js 4.0

### ISSUE THREAD

**Issue by fivdi** [nathanjohnson320/node_arm#13]
Why is it necessary to update the Jessie in order to run Node.js 4? The binaries available at [node.js.org](https://nodejs.org/dist/v4.0.0/) run on Wheezy.

**Comment by fivdi** [comment]
Also, is the Jessie version that gets installed a testing or a stable release?

**Comment by nathanjohnson320** [comment]
I could only get the binaries to not segfault by installing gcc 4.9 manually. It's easier to just upgrade to jessie and do a dist-upgrade than it is to patch and compile gcc myself so that's why I went that route. 

Jessie was officially part of main raspbian back around May, I don't think it's the official version though. If you can find a package of gcc > 4.8 then I could try and include that in the binary.

**Comment by fivdi** [comment]
How do you create the binaries, directly on the Pi itself or by cross compiling?

If they are being created on the Pi, the following will install the optional Raspbian Wheezy gcc & g++ 4.8.2 compilers:
```
sudo apt-get update
sudo apt-get install gcc-4.8 g++-4.8
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.6 20
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.6 20
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
```

**Comment by nathanjohnson320** [comment]
Ah this worked for me and I like it a lot more than forcing an upgrade. I'll update the docs to account for it.

**Comment by zoton2** [comment]
Unfortunately, that method doesn't work for me, unless I'm doing something wrong. 

Did a fresh install of the Debian Wheezy image from the Raspberry Pi site, onto a Raspberry Pi 2 (Model B) and then put those commands in one by one and then installed Node-ARM, but I get the same errors as from issue #11:

```node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by node)```
```node: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.16' not found (required by node)```

I actually tried this twice, just to make sure I didn't mess anything up the first time, but it still didn't work. I also tried upgrading to jessie last night, but it was taking a while (at least over an hour, if not more) and then got stuck on a certain part so I gave up. I will give it another try now though.

**Comment by G3z** [comment]
i'm in the same condition as @zoton2

**Comment by fivdi** [comment]
Raspbian Wheezy 2015-05-05 comes with GLIBC_2.13 and GLIBCXX_3.4.19, but the node_arm binaries require higher versions.

@nathanjohnson320 is is possible to change things so that the Node.js v4.0.0 binaries work with GLIBC_2.13 and GLIBCXX_3.4.19?

**Comment by nathanjohnson320** [comment]
It's a requirement of node.js itself, whenever I try to compile from source it says that those binaries are required.

**Comment by fivdi** [comment]
I don't think it's a requirement of Node.js as the binaries in `node-v4.0.0-linux-armv7l.tar.gz` from https://nodejs.org/dist/latest/ function with GLIBC_2.13 and GLIBCXX_3.4.19 on Raspbian Wheezy 2015-05-05. Unfortunately I don't know how the binaries were built to achieve this.

Here what I see on a Pi 2:

```
pi@raspberrypi ~ $ uname -a
Linux raspberrypi 3.18.11-v7+ #781 SMP PREEMPT Tue Apr 21 18:07:59 BST 2015 armv7l GNU/Linux
```

```
pi@raspberrypi ~ $ ldd --version
ldd (Debian EGLIBC 2.13-38+rpi2+deb7u8) 2.13
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

```
pi@raspberrypi ~ $ strings /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 | grep LIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

```
pi@raspberrypi ~ $ node -v
v4.0.0
pi@raspberrypi ~ $ node
> Date()
'Tue Sep 15 2015 21:44:11 GMT+0200 (CEST)'
> 
```

**Comment by nathanjohnson320** [comment]
I don't think you should use node-arm if you're on an Pi 2 this is specifically for the B/B+ models for the RPI2 you should be using https://github.com/nodesource/distributions

I'll post an issue on the node.js repo to figure out how to run ./configure without the GLIBC errors for the RPI 1

**Comment by fivdi** [comment]
Ok, I wasn't aware that node_arm is specifically for the Pi 1 B/B+. Good luck with the issue at the Node.js repo.

**Comment by fivdi** [comment]
https://github.com/nodejs/node/issues/2876 appears to be the same issues but in a different environment.

**Comment by fivdi** [comment]
Now that [Raspbian Jessie](https://www.raspberrypi.org/downloads/raspbian/) has been released, this is probably no longer an issue.

**Comment by nathanjohnson320** [comment]
Yep I'm gonna go ahead and close this one out.
