### ISSUE TITLE
archive link save as

### ISSUE THREAD

**Issue by jacobrosenthal** [nathanjohnson320/node_arm#14]
Greetings, 
Jacob from [node-serialport](https://github.com/voodootikigod/node-serialport) here. Thanks for hosting installs. Were hoping to link to them in our readme. 
For latest, we can use
```
wget http://node-arm.herokuapp.com/node_latest_armhf.deb
sudo dpkg -i node_latest_armhf.deb
```
but archive saves a file called node_0.12.6-1.armhf.deb which I presume at any time could be updated to 12.7 and wed have to update our docs again. What do you think about making the file name you save as consistent with latest, ie node_archive_armhf.deb?

Thanks again,
Jacob

**Comment by nathanjohnson320** [comment]
Just pushed an update for this. I don't anticipate upgrading to 0.12.7 since it's still broken on the RPI and I doubt it will ever be fixed but I updated the routes just in case.

**Comment by jacobrosenthal** [comment]
Thanks!
