### ISSUE TITLE
Version 4.2.1 for arm?

### ISSUE THREAD

**Issue by stozk** [nathanjohnson320/node_arm#18]
Hi,

your readme states

"This will install node.js version 4.2.1...", but when I run the command (on a Raspberry Pi):

wget http://node-arm.herokuapp.com/node_latest_armhf.deb
sudo dpkg -i node_latest_armhf.deb

It will install some 0.10.x version... and the latest unstable installs v0.11.16-1

Is this normal?

I would have expected node -v to return v4.2.1 as it does on my Windows install...

BR
Daniel

**Comment by nathanjohnson320** [comment]
I'll need to double check when I'm off work. I tested it on both my Pis before and after I deployed and got v4.2.1 so I'm not sure why it would be installing the old 0.10 version

**Comment by stozk** [comment]
It actuall even downgraded from my initial v.0.12 ;-)

But it would be great if you manage to check, thx&BR

**Comment by nathanjohnson320** [comment]
Can you try
```
wget https://github.com/nathanjohnson320/node_arm/blob/master/routes/files/node_4.2.1-1_armhf.deb
sudo dpkg -i node_4.2.1-1_armhf.deb
```

This will help me to figure out if it's the package itself or the routes being messed up.

**Comment by stozk** [comment]
That archive seems to be broken, it's only 27bytes...

**Comment by nathanjohnson320** [comment]
it says it's 5.36 MB in the repo.

> On Oct 19 2015, at 11:22 am, Daniel &lt;notifications@github.com&gt; wrote:  

>

> That archive seems to be broken, it's only 27bytes...

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nathanj
ohnson320/node_arm/issues/18#issuecomment-149248096).![](https://github.com/no
tifications/beacon/ABmj1XaeIQN8bBIBOsNvSM-CfXlSStsIks5o9QI5gaJpZM4GRazU.gif)

**Comment by stozk** [comment]
I downloaded it manually and uploaded it to the pi via ftp, but when it would tell me that it's not a debian format archive.

**Comment by stozk** [comment]
Sorry, something went wrong during the upload and it didn't overwrite the original broken file. 
The latest file works, but now it's complaining I'm missing "GLIBBCXX_3.4.20" ;-)

It'll try to fix that but in general the file you posted should work I guess

**Comment by stozk** [comment]
Ah well ok I just noticed that I need the jessie release, this one is still on wheezy....

https://github.com/nathanjohnson320/node_arm/issues/13

**Comment by stozk** [comment]
And I also think that the node_latest_armhf.deb was just fine, but I didn't notice that the system put a ".1" because I already had an older install file on there... sorry for that again.
