### ISSUE TITLE
wheezy to jessie help

### ISSUE THREAD

**Issue by emps** [nathanjohnson320/node_arm#19]
Options 2: Upgrade to debian Jessie
Replace all instances of "wheezy" in /etc/apt/sources.list

replace with what ?

thanks..

**Comment by emps** [comment]
cause Option 1 didnt help still same lib problem
node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by node)

**Comment by nathanjohnson320** [comment]
replace with "jessie"

If you don't have anything critical on your Pi you can download the newest raspbian image and then apt-get install gcc-4.8 g++-4.8
