### ISSUE TITLE
update for v0.10.36? v0.11.x support

### ISSUE THREAD

**Issue by coolaj86** [nathanjohnson320/node_arm#3]
Would love to see it.

**Comment by nathanjohnson320** [comment]
Might have to change the URL structure for this but I'll get started on it later tonight.

**Comment by nathanjohnson320** [comment]
There's an open issue for compiling 0.11.6 until that's resolved or a working patch is released this will be put on hold.

**Comment by nathanjohnson320** [comment]
So I think they got this patched I'm compiling it now hopefully have it up later tonight.

**Comment by nathanjohnson320** [comment]
http://node-arm.herokuapp.com/node_latest_unstable_armhf.deb

:)
