### ISSUE TITLE
.deb file available as a repository in sources.list?

### ISSUE THREAD

**Issue by eklem** [nathanjohnson320/node_arm#5]
So we can do 
```console
apt-get update 
apt-get upgrade
```

Or is that not wanted since it may lead to unwanted upgrades?

**Comment by eklem** [comment]
And, thinking about it, that last issue can be solved by not installing the latest package for when you're in a production environment.

**Comment by nathanjohnson320** [comment]
I didn't want to setup a whole repository just for one package. It may be useful if I start compiling the different node versions (0.11, 0.12, etc.) but I haven't had a huge demand for that yet.

I think it might be worth the time though so I'll investigate this later tonight.

**Comment by eklem** [comment]
Cool! I was thinking a bit back and forth why this felt important and came up with this: A lot of times I install something that's not in the repository, and I forget from which source I installed. That will make for a headache later. Anyway: Great repository and website!

**Comment by nathanjohnson320** [comment]
Give this a shot :)
```
echo "deb http://node-arm.herokuapp.com/ /" | sudo tee --append /etc/apt/sources.list
sudo apt-get update
sudo apt-get install node
node -v
```

**Comment by eklem** [comment]
Thanks, works great!

```console
pi@raspberrypi ~ $ node -v
v0.12.0
pi@raspberrypi ~ $ npm -v
2.5.1
```

**Comment by eklem** [comment]
And I've tested it on Raspberry Pi Model B (the one with 256 MB RAM) on the Raspbian image:
http://www.raspberrypi.org/downloads/

**Comment by eklem** [comment]
And tested on the latest Raspberry Pi 2 with Raspbian image installed:
http://www.raspberrypi.org/downloads/
