### ISSUE TITLE
Update to node 0.12.7

### ISSUE THREAD

**Issue by siruba757d** [nathanjohnson320/node_arm#9]
I tried to compile on RPI1 momdel B with no luck. On RPI2 model B it compiles ok.

Regards

**Comment by nathanjohnson320** [comment]
Can you post the output of the install? It also shouldn't be doing any compilation it's just a package.

**Comment by nathanjohnson320** [comment]
They still haven't merged the branch that fixes an issue with compiling on Armv6 that's why it fails on the Rpi 1. I'll try to push a fix later this week

**Comment by nathanjohnson320** [comment]
Meant to post on this a couple weeks ago but I've been out of town.

I applied the patch that used to work to fix npm but for some reason this doesn't work anymore and there's a new issue that popped up preventing npm from working. I tried io.js and it still works so until they merge node/io I'd go with that for now.

**Comment by siruba757d** [comment]
I switched to RPI2 and it works fine. Maybe RPI1 is not a good idea since I had to patch v0.12.2 and 0.12.7 is giving problems also. I hope problems will be solved for nodejs when totally merged with io.js

Thank you very much!
